require 'REXML/document'
require 'pp'
require 'fileutils'
require 'strscan'
require 'stringio'

require_relative 'nif_version'
require_relative 'nif_type'
require_relative 'nif_basic'
require_relative 'nif_option'
require_relative 'nif_bitflags'
require_relative 'nif_enum'
require_relative 'nif_field'
require_relative 'nif_compound'
require_relative 'nif_niobject'
require_relative 'nifxml'
require_relative 'expression_parser'
